import os
from google import genai

# Configuration
MD_FILE = "Solar_PV_Forecasting_Journal_Paper.md"
REPORT_FILE = "anti_hallucination_report.md"

def get_api_key():
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("ERROR: GEMINI_API_KEY environment variable not set.")
        exit(1)
    return api_key

def main():
    api_key = get_api_key()
    
    # Initialize the client from the new `google-genai` SDK
    client = genai.Client(api_key=api_key)
    
    if not os.path.exists(MD_FILE):
        print(f"File {MD_FILE} not found.")
        return

    print(f"Reading {MD_FILE}...")
    with open(MD_FILE, "r", encoding="utf-8") as f:
        content = f.read()
        
    print("Starting Anti-Hallucination verification via Gemini API...")
    
    prompt = f"""
    You are an expert academic reviewer and scientific fact-checker specializing in Renewable Energy, Solar PV Systems, and Machine Learning.
    
    Review the following academic paper strictly as an "anti-hallucination" verification tool.
    
    Your tasks:
    1. Identify any technical claims, statistics, or metrics in this text that seem factually incorrect, highly suspicious, or potentially hallucinated based on current scientific consensus.
    2. Check models/baseline comparisons (e.g. LSTM, ANN sizes/hyperparameters) to see if they make physical or theoretical sense.
    3. Verify standard metrics (RMSE, MAE, R², etc.). Point out if the numbers presented are "too good to be true" (e.g., an R² of 0.999 on chaotic irradiance data).
    
    For each potentially hallucinated or weak claim, provide:
    * **Claim**: The original claim/text from the paper.
    * **Suspicion**: Why it might be a hallucination or an error.
    * **Correction/Consensus**: What the actual scientific consensus or correct physical limit is.
    
    Organize your report logically by sections of the paper.
    If the paper is fundamentally correct, state that no major hallucinations were detected but point out the strongest or weakest factual links.

    --- PAPER CONTENT ---
    
    {content}
    """
    
    try:
        print("Sending paper data to Gemini... (This could take roughly 10-30 seconds)")
        
        # We use a standard fast and capable model from Gemini. 
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=prompt,
        )
        report_content = response.text
        
        print(f"Writing report to {REPORT_FILE}...")
        with open(REPORT_FILE, "w", encoding="utf-8") as f:
            f.write("# Anti-Hallucination Report\n\n")
            f.write(f"Generated by Google Gemini API.\n\n")
            f.write(report_content)
            
        print("Done! Review the report for any hallucinated claims.")
        print(f"Report Location: {REPORT_FILE}")

    except Exception as e:
        print(f"Error querying Gemini API: {e}")
        print("Attempting fallback to gemini-1.5-pro...")
        try:
            response = client.models.generate_content(
                model='gemini-1.5-pro',
                contents=prompt,
            )
            report_content = response.text
            
            with open(REPORT_FILE, "w", encoding="utf-8") as f:
                f.write("# Anti-Hallucination Report\n\n")
                f.write(f"Generated by Google Gemini API.\n\n")
                f.write(report_content)
                
            print(f"Done using fallback model! Report Location: {REPORT_FILE}")
        except Exception as e2:
             print(f"Fallback Error: {e2}")

if __name__ == "__main__":
    main()
